### ISSUE TITLE
k10temp reporting duplicates

### ISSUE THREAD

**Issue by shayaantx** [groeck/k10temp#13]
Hello,

Running centos7, 3.10.0-1062.7.1.el7.x86_64

I manually installed https://github.com/groeck/k10temp module since the one that comes with this kernel doesn't display tdie or tctl for all cpus (cpu = Threadripper 2920X)

It seems to be duplicating the temperature twice (see below). Before I installed the updated module, it didn't display tdie or tctl. Should just try upgrading kernel instead?

Any ideas?

[root@dedicated-server ~]# sensors
k10temp-pci-00c3
Adapter: PCI adapter
Tdie: +30.4°C (high = +70.0°C)
Tctl: +57.4°C

k10temp-pci-00cb
Adapter: PCI adapter
Tdie: +30.4°C (high = +70.0°C)
Tctl: +57.4°C

**Comment by groeck** [comment]
Older kernels don't have the necessary infrastructure and do indeed report the temperature of the first die twice. I have no idea if the necessary infrastructure code has been backported to Centos7. SInce Centos7 has substantially deviated from upstream, I would recommend to either stick with what it provides or to switch to a more recent kernel.

**Comment by shayaantx** [comment]
yea I switched to latest mainline kernel and it started showing diff temps, thanks
